import type { NextPage } from 'next'
import Head from 'next/head'

import { useTodoContext } from '../contexts/todo'
import { Layout } from '../components/Layout'
import { Button } from '../components/shared/Button'

const Home: NextPage = () => {
  const { archived, removeList } = useTodoContext()

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {
          archived.length > 0 && (
            <>
              <h1>Archived</h1>
              {archived.map(list => (
                <div key={list.id}>
                  <h2>{list.title} - {list.id}</h2>
                  <Button
                    onClick={() => removeList(list.id)}
                  >
                    Remove
                  </Button>
                </div>
              ))}
            </>
          )
        }
      </Layout>
    </>
  )
}

export default Home
