import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout } from '../components/Layout'
import { Tasks } from '../components/Tasks'

const Home: NextPage = () => {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Tasks />
      </Layout>
    </>
  )
}

export default Home
