import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout } from '../components/Layout'

import { useTodoContext } from '../contexts/todo'

const Home: NextPage = () => {
  const { lists } = useTodoContext()

  useEffect(() => {
    const localItems = localStorage.getItem('items')
    if (localItems) {
      // setItems(JSON.parse(localItems))
    }
  }, [])

  useEffect(() => {
    console.log('items', lists)
  }, [lists])

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {lists.find(todo => todo.active === true) ? (
          <h2>
            {lists.find(todo => todo.active === true)?.title}
          </h2>
        ) : (
          <p>No active todo</p>
        )}
      </Layout>
    </>
  )
}

export default Home
