import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

import { Layout } from '../components/Layout'
import { ModalAddNewList } from '../components/Modals'
import { Button } from '../components/shared/Button'
import { useTodoContext } from '../contexts/todo'


const Lists: NextPage = () => {
  const { listActive, addList } = useTodoContext()
  const [isModalAddNewListOpen, setIsModalAddNewListOpen] = useState(false)

  if (!listActive) {
    return (
      <>
        <p>No list selected.</p>
        <Button onClick={() => setIsModalAddNewListOpen(true)}>Create a new list</Button>
        <ModalAddNewList
          isOpen={isModalAddNewListOpen}
          onRequestClose={() => setIsModalAddNewListOpen(false)}
          addNewList={addList}
        />
      </>
    )
  }

  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Lists</h1>

      </Layout>
    </>
  )
}

export default Lists
